/*
 * action 类型
 */

//TODO
export const REQUEST_TODOS = 'REQUEST_TODOS';
export const RECEIVE_TODOS = 'RECEIVE_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
//INQUIRY
export const REQUEST_INQUIRIES = 'REQUEST_INQUIRIES';
export const RECEIVE_INQUIRIES = 'RECEIVE_INQUIRIES';
//PRODUCT
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
//PERSON
export const REQUEST_PERSON = 'REQUEST_PERSON';
export const RECEIVE_PERSON = 'RECEIVE_PERSON';

//MESSAGE
export const  REQUEST_ERROR_LOG = 'REQUEST_ERROR_LOG';
export const  RECEIVE_ERROR_LOG = 'RECEIVE_ERROR_LOG';

/*
 * FILTER
 */
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
};
